### ISSUE TITLE
Not updated with latest map

### ISSUE THREAD

**Issue by Brmallen** [cesar-rgon/simple-kf2-server-launcher#11]
Needs to be updated with latest map.

**Comment by cesar-rgon** [comment]
Hi.
I'm terrible sorry for not answer you much time before.
The project has been paused a long time for personal reasons that occupied my free time.

Now i can resume the project and I'm developing v2.0.5 in a new branch.
It is in alpha version but it can be cloned ans tested for feedback.

In this new version I have included all new official maps by default.

I'm working to finish the release as soon as possible.

Regards.

**Comment by cesar-rgon** [comment]
Hi.
v2.0.5 and v.2.0.6 have been published.
New maps are included by default in the launcher.

I close the ticket. Le me know if you have a new problem.

Regards.
