### ISSUE TITLE
Missing Asylum Map

### ISSUE THREAD

**Issue by agustinsau** [cesar-rgon/simple-kf2-server-launcher#4]
Hello! First of all, nice work with the launcher, i really apreciate it! Now the problem is... that i downloaded the last killing floor 2 version, and the last new map isnt appearing in the map list. So what i did were reconfig the PCServer-KFGame file, adding the map new entrys. Fine, the map is now appearing on WebAdmin. The new problem was, that when i reopen the launcher again, overwrites the PCServer-KFGame i have already edited. And back to start again. The only way i can fix this by now is remplacing the .ini file every time i open my server. Can you help me with this? 
Thanks a lot dude.
Cheers, MetalThunder

**Comment by ghost** [comment]
You have to click on import in the map/mods section

**Comment by agustinsau** [comment]
Mmm yes, i tried that too.. but some error about missing download cache appeared

**Comment by agustinsau** [comment]
So i copied the new map folder into the cache folder (i created one) and then yes, pressed on Import and it works, the map was added to the list of official maps. But then again, when i close the launcher, have to import again.

**Comment by ghost** [comment]
I might know the issue. The program checks to see if there is anything in cache to import. If there isn't then it won't start the importing process. 

If you subscribe to any workshop item through the launch you won't need to do anything to your files.

I'm also having the issue of needed to import the map each time I open the launcher.

**Comment by cesar-rgon** [comment]
Hello @MetalThunder66 and @IsaacParnell 
First of all, thank you very much for your feedback.

It's strange, i have not the described issue in my server with the launcher.
Have you got several profiles @MetalThunder66 ?

In that case, note that when you import maps/mods, you import them for the selected profile (not for other profiles). I explain myself with an example:

Profile1: You have 27 official maps.
Profile2: You have 27 official maps too.

**Select Profile1** (**In Maps/Mods menu**, do not confuse with Main Page menu) --> **Import maps/mods** --> The new official map, custom maps and mods are imported ONLY for Profile1, that means:

**Profile1**: You have **28 official maps + custom maps/mods**
**Profile2**: You still have **27 official maps only**.

If you want to import maps/mods for Profile2 you have to repeat the operation for this profile: 
Select Profile2 --> Import maps/mods.

Is that your problem? Are you importing maps/mods always for profile1 and when you select profile2 you don't see them?
If that's not your problem, can you send me the "launcher.log" file placed in the launcher's folder? (a screenshot with the error message window may help too).

The import process checks not only cache folder (searching custom maps/mods) but also KFGame\BrewedPC\Maps folder (searching official maps). There is not need to copy an official map's folder to Cache folder.

I wait your answer.
Regards.

**Comment by agustinsau** [comment]
Hello cesar! thanks for you reply :) i have one profile only, thats strange. I finished puting the new map in the cache folder, because otherwise the error i mentioned you before appeared.
Now i open the launcher again, to check if i had to add the new map again and its already there in my default profile, from yesterday (last time i used the launcher) 👍 To be sure that the problem is solved, i created a new profile and i have all 28 official maps too. Thanks a lot! i think the import thing solved it. The strange thing is that error i got when i tried to import the map (without passing the official map to the cache folder yet).
Keep it up the great work!
Regards.

**Comment by cesar-rgon** [comment]
Hi @MetalThunder66 
The new release v2.0.2 has been developed.
Now you can add/import maps to multiple profiles at once.
Furthermore the new map "Ashwood Asylum" is included in the launcher by default.

Regards.
