### ISSUE TITLE
[enhancement] Improvements for the Maps/Mods import feature.

### ISSUE THREAD

**Issue by ghost** [cesar-rgon/simple-kf2-server-launcher#5]
I would like to be able to choose what new workshop items get added to what profile.

Something like this would be good.
![this](https://user-images.githubusercontent.com/33142754/66006852-7bfee900-e4f3-11e9-9b45-da0b7044bc5b.png)
#fixed image-(I'm new to GitHub)

**Comment by cesar-rgon** [comment]
Hi @IsaacParnell 
When you add new maps/mods or import them, they will be vinculated to the actual selected profile (the profile selected in Maps/Mods combo).

If you want to vinculate the maps for other profiles, you have to select the others profiles and repeat the operation.
Do you think that is a problem?

I understand that you want to vinculate maps to multiple profiles at a same time when you add them to the launcher as well as when you import them. have I understood you well?

Regards.

**Comment by ghost** [comment]
I'll tell you my situation first. I have linked the maps and mods from my game to the server. So when I download maps and mods through steam, but my game and the server can access them. I do this because I want to save space on my boot drive which is the default install location.

The reason why I want to be able to choose what maps get added is because I have some workshop items installed that I don't want the server to use. So ideally, when I go to add new maps and mods, I want to be able to opt out the ones that I don't want on the server. It would also be ideal to only need to do this process once as it will take a while when handling many workshop items and profiles.

The suggestion I mentioned up above is an idea that will solve both of these issues in one go.

**Comment by cesar-rgon** [comment]
Ok.
These days i'm in hollydays. Next week i will start to implement that for the next version of the launcher.
I think it would be useful for:

* Add custom maps/mods (by id/url WorkShop)
* Add a single map/mod (through Steam's WorkShop pages)
* Remove maps/mods
* Import maps/mods

By the way, only if you didn't know it, you do not need to subscribe to the maps that you are going to add to the launcher. It's just enouth to add the map to the launcher, when you join to the server, the map will be downloaded automatically in the client.

Regards.

**Comment by cesar-rgon** [comment]
Hi @IsaacParnell 
The new release 2.0.2 has been developed.
Now you can add/import maps to multiple profiles at once.

I hope you can find it useful.
Regards.

**Comment by ghost** [comment]
Hi @cesar-rgon, it's been a while. Your application has served me well since my last comment. It has been perfectly reliable and stable. 

I have used the feature of choosing the profiles for where the latest mods are imported, however this process is still slow for me.

When I have clicked import, and chosen the profiles, I would like to see another pop up to choose exactly which mods get imported.

I understand that I can do something similar by using the mods IDs but that process is slow and tedious.

Do note that I am not your average user. These problems won't occur for many people. It's just that I am constantly updating and changing the mods on my servers. So there is no need to implement this feature. I am just giving you more to do if you ever get bored.

On that note, there is another feature that is more important as more people will use it. I would like to see more webadmin settings in your launcher, particularly multiwebadmin settings.

I'll leave you with that novel to read and if you need any information about what I'm talking about just contact me. Thank you once again for this beautiful application, I use it daily.

**Comment by cesar-rgon** [comment]
Hi @IsaacParnell 

Thank you very much for your words.
I enjoy that you can find the application useful.

What WebAdmin's setting do you think that are important to be included in the launcher?

Regards.

**Comment by ghost** [comment]
Team Collision, Admin pausing, and chat logging. I would also like to see multiadmin settings or at least copy the multiadmin settings over when a profile is cloned. 

To enable and access multiadmin, the line `AuthenticationClass=WebAdmin.MultiWebAdminAuth` needs to be placed under the _[WebAdmin.WebAdmin]_ section of the _KFWebAdmin.ini_ file. 

The multiadmin settings is stored in the _KFMultiAdmin.ini_ file.

**Comment by cesar-rgon** [comment]
Ok.
Take a look to the "things to do for next releases" page and let me know if you think something is miss

https://github.com/cesar-rgon/simple-kf2-server-launcher/wiki/Things-TODO-for-next-releases

Regards.

**Comment by ghost** [comment]
Perfect

**Comment by ghost** [comment]
Alright. I feel bad for giving you so much work but there is one small feature that I could strongly benefit from. I would like it if I could run a file at server launch. It doesn't even need to be per server. Just whenever I click okay after clicking run servers I want a bat file to start up automatically. 

I would like this feature because I have just made a batch file that can automatically generate a config file for [Killing Floor 2 Magicked Admin](https://github.com/th3-z/kf2-magicked-admin) and launch it.

**Comment by cesar-rgon** [comment]
Hi @IsaacParnell 
I can't understand very well the need of that functionallity,
is not enougth to run a server with a profile and custom parameters?
Furthermore you can execute the launcher from a batch file with the command:
java -jar SimpleKF2ServerLauncher.java --profiles MyProfile

can i see an example of the content of the batch file?
i need to understand well the functionallity before implementate it.

Thanks.
Regards.

**Comment by ghost** [comment]
[This](https://pastebin.com/P4xufe1P) is the file I want to run. What it does its look through the launch log files and grabs the name and port of each server. It then uses this information to create a config file for the statbot I use. This file still needs some work and I will make some changes but that is essentially what I want.

**Comment by cesar-rgon** [comment]
Ok, I see.
I will implementate that feature too.
Regards.

**Comment by cesar-rgon** [comment]
Hi @IsaacParnell 
Finally, i have published the new release of the launcher: v2.0.4 with more parameters and options.
You can see new features in the download section of the project.

MultiAdmin settings feature will be implemented for a future release.

I hope you can find useful.
Regards.

**Comment by cesar-rgon** [comment]
Sorry, i forgot to tell you how to run your batch file after click "Run Server" button.

Edit and setup the file:
LAUNCHER_ROOT_FOLDER\properties\config.properties

For example:
```
prop.config.enableExecuteFileBeforeRunKF2Server=true
prop.config.executeFileViaConsole=true
prop.config.fileToBeExecuted=C:\\path\\to\\your\\file\\example.bat
```

Replace the last line with the path to your file.
On Windows the separator for the folders is "\\\\"
On Linux the separator for the folders is "/" (should work on Windows too)

Regards.

**Comment by ghost** [comment]
Excellent work. I everything works perfectly.
