### ISSUE TITLE
Excelent

### ISSUE THREAD

**Issue by rpercastro** [cesar-rgon/simple-kf2-server-launcher#6]
Excellent application I love the way you use the new technique of "virtual land", very optimized and efficient, demonstrating a mastery of this technique that today is doubtful of more than one of those who are dedicated to computer technologies. Great job. Congratulations!

**Comment by cesar-rgon** [comment]
Hi @rpercastro 
I don't understand your words very well, but thank you very much for your enthusiasm.

Regards.

**Comment by rpercastro** [comment]
Hi @ cesar-rgon,

Your new version seems very useful. But from my point of view you need to apply the concept of virtual earth more deeply, even though I think you are not aware of how you have involved your application in this technology. I will contact Mr. Gumersindo, one of the most advanced people in the implementation of this new technology and I will tell him to join this thread as a follower. He will be happy to contribute his knowledge as a seminar and you can increase your knowledge about this technique.

Regards.

**Comment by rpercastro** [comment]
Impresive!!!

Regards
