### ISSUE TITLE
Cannot add custom maps

### ISSUE THREAD

**Issue by 96dervalics** [cesar-rgon/simple-kf2-server-launcher#7]
If I try to add custom maps via the Workshop it doesnt show the Add button, also I cant set the map id, I got No maps/mods were added message.

I tried to use the ID and also the URL.

**Comment by Borsoi** [comment]
I'm having the same issue, the project had been abandoned?

**Comment by cesar-rgon** [comment]
Hi.
I'm terrible sorry for not answer you much time before.
The project has been paused a long time for personal reasons that occupied my free time.

Now i can resume the project and I'm developing v2.0.5 in a new branch.
At this moment, it is in alpha version but it can be cloned and tested for feedback.

In this new version I have fixed the custom maps/mods functionality and now they can be added to the launcher as espected.

I'm working to finish the release as soon as possible.

Regards.

**Comment by cesar-rgon** [comment]
Hi.
v2.0.5 and v.2.0.6 have been published.
Custom maps can be added to the launcher again.

I close the ticket. Le me know if you have a new problem.

Regards.
