### ISSUE TITLE
Can't Run Server

### ISSUE THREAD

**Issue by Aeyori** [cesar-rgon/simple-kf2-server-launcher#8]
I'm trying to create a server on a separate computer without KF2 installed and I'm getting this error:

C:\KillingFloor2\KFGame\Config\Default\PCServer-KFEngine.ini (The system cannot find the file specified)
https://pastebin.com/W6miTpgS

**Comment by Aeyori** [comment]
I just tested on my PC with KF2 on it and it worked but still doesn't on the other computer without it

**Comment by Tapok777** [comment]
https://steamdb.info/depot/232131/
PCServer-KFEngine.ini
KFWeb.ini
these files no longer exist for the server, the application needs to be updated.

**Comment by cesar-rgon** [comment]
Hi.
I'm terrible sorry for not answer you much time before.
The project has been paused a long time for personal reasons that occupied my free time.

Now i can resume the project and I'm developing v2.0.5 in a new branch.
It is in alpha version but it can be cloned ans tested for feedback.

The launcher has not been tested to launch a remote KF2 server.
¿Can be executed the launcher in the remote computer? This is the easiest way, i think.

Another solution could be to mount a network unit in your computer and try to execute the launcher.

I'm going to test it and try to find a solution.


I'm working to finish the release as soon as possible.

Regards.
